### ISSUE TITLE
Missing analytics "authenticated" events on Auth0 hosted pages

### ISSUE THREAD

**Issue by stuartwakefield** [auth0/auth0-tag-manager#9]
Adding GA analytics to a Auth0 hosted page. If the user signs in successfully we are not seeing the "authenticated" event appearing in Google Analytics. It may be that the browser is redirected before the event has been sent to analytics. May need to use [hitCallback][hit-callback] when analytics is enabled

[hit-callback]: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hitCallback

**Comment by ntotten** [comment]
We will take a look at this today.

**Comment by francocorreasosa** [comment]
Hi @stuartwakefield, are you directly using tag-manager and listening to the event manually? or are you using [Analytics.js](https://github.com/auth0/auth0-analytics.js)?

**Comment by ntotten** [comment]
@stuartwakefield since we haven't heard back we are closing this issue. Please feel free to reopen if needed.
